### ISSUE TITLE
Clean and remove the old shapefile and data

### ISSUE THREAD

**Issue by nikeshbalami** [CodeforNepal/nepalmap2021#3]
To populate the NepalMap with the new census data, we need to remove the old datasets which are in the SQL.

**TODO**
- [x] Analyse the old datasets which need to be removed
- [x] Remove and clean the both (shapefile and datasets)
- [x] Submit the PR for the review

**Comment by nikeshbalami** [comment]
Closing. Solved in #13
