### ISSUE TITLE
Clean and remove the old data

### ISSUE THREAD

**Issue by nikeshbalami** [CodeforNepal/nepalmap2021#3]
The current version of the NepalMap uses the old shapefile and data. The plan is to remove the old files so that both shapefile and data can be updated with new ones.

**Tasks**
- [ ] Deploy the NepalMap in your local
- [ ] Go through and understand the codebase
- [ ] Clean and remove the old datasets
