### ISSUE TITLE
Update the new shapefile (the one with Kalapani and Lipulekh)

### ISSUE THREAD

**Issue by nikeshbalami** [CodeforNepal/nepalmap2021#5]
As the old shapefile and data have been removed. Update the NepalMap with the updated shapefile. This is also important, the old shapefile has many issues as mentioned in the old repo: https://github.com/CodeforNepal/nepalmap_federal/issues

**TODO**
- [x] Make sure the old shapefile has been removed
- [x] Go to https://localboundries.oknp.org/ to obtain the new shapefile
- [x] Update the NepalMap with new shapefile

**Comment by nikeshbalami** [comment]
Closing. Solved in #13
