### ISSUE TITLE
Update the new preliminary population data from the 2021 census

### ISSUE THREAD

**Issue by nikeshbalami** [CodeforNepal/nepalmap2021#6]
As our idea in the update is to update the new preliminary population data from the 2021 census so that we can make further updates quickly once the full census data is published.

For now, the plan is the populate the NepalMap with preliminary data.

**TODO**
- [x] Make sure the old datasets are removed
- [x] Go to https://opendatanepal.com/dataset/preliminary-data-of-national-population-and-housing-census-2021 to obtain the data
- [x] Update the NepalMap with new datasets
- [x] Submit PR for the review

**Comment by nikeshbalami** [comment]
Done with #13
